src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?int $Price = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $Category = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $mediaUri = null;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->Price;
    }

    public function setPrice(int $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getMediaUri(): ?string
    {
        return $this->mediaUri;
    }

    public function setMediaUri(?string $mediaUri): self
    {
        $this->mediaUri = $mediaUri;

        return $this;
    }

}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Service\CartService;
use Doctrine\ORM\Mapping\Id;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;

class CartController extends AbstractController
{
    #[Route('/cart', name: 'cart')]
    public function index(CartService $cartService): Response
    {
        return $this->render('cart/index.html.twig', [
            'cart' => $cartService->getTotal(),
        ]);
    }
    

    #[Route('/add/{id}', name: 'add', requirements: ['id' => '\d+'])]
    public function addToCart(int $id, CartService $cartService, Request $request)
    {
        $quantity = $request->get('quantity'); // Retrieve quantity directly from request
        $cartService->addToCart($id, $quantity);
        return $this->redirectToRoute('cart');
    }
    
    

    #[Route('/remove/{id}', name:'remove', requirements: ['id' => '\d+'])]
    public function removeToCart(int $id, CartService $cartService)
    {
        $cartService->removeToCart($id);
        return $this->redirectToRoute('cart');
    }

    #[Route('/update/{id}', name: 'update_quantity', requirements: ['id' => '\d+'])]
    public function updateCartItem(int $id, CartService $cartService, Request $request)
    {
        $quantity = $request->get('quantity');
        $cartService->updateQuantity($id, $quantity);
        return $this->redirectToRoute('cart');
    }
    
    #[Route('/checkout', name: 'checkout')]
    public function thankYou(CartService $cartService): Response
    {
        $cart = $cartService->getTotal();
        $total = $cartService->calculateTotal($cart); // Replace `calculateTotal()` with your logic to calculate the total
        
        // Clear the cart
        $cartService->clearCart();
    
        return $this->render('cart/checkout.html.twig', [
            'cart' => $cart,
            'total' => $total,
        ]);
    }
    
    
}

templates/cart/checkout.html.twig
{# cart/thank_you.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Thank You{% endblock %}

{% block body %}
    <div class="container">
        <h1>Thank You for Your Purchase!</h1>
        <p>We appreciate your business.</p>

        <h2>Order Details:</h2>
        <ul>
            {% for item in cart %}
                <li>
                    Product: {{ item.product.title }}
                    Quantity: {{ item.quantity }}
                    Price: {{ item.product.price }}€
                </li>
            {% endfor %}
        </ul>

        <h3>Total: {{ total }}€</h3>
    </div>
{% endblock %}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CartController!{% endblock %}

{% block body %}

<section class="pt-5 pb-5">
  <div class="container">
    <div class="row w-100">
        <div class="col-lg-12 col-md-12 col-12">
            <h3 class="display-5 mb-2 text-center">Shopping Cart</h3>
            <table id="shoppingCart" class="table table-condensed table-responsive">
                <thead>
                    <tr>
                        <th style="width:60%">Product</th>
                        <th style="width:12%">Price</th>
                        <th style="width:10%">Quantity</th>
                    </tr>
                </thead>
                <tbody>
                {% set total = 0 %}
                {% for item in cart %}
                    <tr>
                        <td data-th="Product">
                            <div class="row">
                                <div class="col-md-3 text-left">
                                    <img src="{{ asset(item.product.mediaUri) }}" alt="" class="img-fluid d-none d-md-block rounded mb-2 shadow ">
                                </div>
                                <div class="col-md-9 text-left mt-sm-2">
                                    <h4>{{ item.product.title }}</h4>
                                    <p class="font-weight-light">Category - {{ item.product.category.name }}</p>
                                </div>
                            </div>
                        </td>
                        <td data-th="Price">{{ item.product.price }}€</td>
                        <td data-th="Quantity">
                                <form action="{{ path('update_quantity', {'id': item.product.id}) }}" method="POST">
                                <input type="number" name="quantity" value="{{ item.quantity }}" min="1">
                        </td>

                        <td class="actions" data-th="">
                            <div class="text-right">
                                <button type="submit"href="" class="btn btn-white border-secondary bg-white btn-md mb-2">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-repeat" viewBox="0 0 16 16">
                                    <path d="M11.534 7h3.932a.25.25 0 0 1 .192.41l-1.966 2.36a.25.25 0 0 1-.384 0l-1.966-2.36a.25.25 0 0 1 .192-.41zm-11 2h3.932a.25.25 0 0 0 .192-.41L2.692 6.23a.25.25 0 0 0-.384 0L.342 8.59A.25.25 0 0 0 .534 9z"/>
                                    <path fill-rule="evenodd" d="M8 3c-1.552 0-2.94.707-3.857 1.818a.5.5 0 1 1-.771-.636A6.002 6.002 0 0 1 13.917 7H12.9A5.002 5.002 0 0 0 8 3zM3.1 9a5.002 5.002 0 0 0 8.757 2.182.5.5 0 1 1 .771.636A6.002 6.002 0 0 1 2.083 9H3.1z"/>
                                    </svg>
                                </button>                              
                            </form>
                            
                                <a href="{{ path('remove', {'id': item.product.id}) }}" class="btn btn-white border-secondary bg-white btn-md mb-2">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                                        <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
                                    </svg>
                                </a>
                            </div>
                        </td>
                    </tr>
                {% set total = total + (item.quantity * item.product.price) %}
                {% endfor %}
                </tbody>
            </table>
            <div class="float-right text-right">
                <h4>Total:</h4>
                <h1>{{ total }}€</h1>
            </div>
        </div>
    </div>
    <div class="row mt-4 d-flex align-items-center">
        <div class="col-sm-6 order-md-2 text-right">
        <a href="{{ path('checkout') }}" class="btn btn-primary mb-4 btn-lg pl-5 pr-5">Checkout</a>

        </div>
        <div class="col-sm-6 mb-3 mb-m-1 order-md-1 text-md-left">
            <a href="{{ path('app_home')}}">
                <i class="fas fa-arrow-left mr-2"></i> Continue Shopping</a>
        </div>
    </div>
</div>
</section>

    
{% endblock %}